modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="https://github.com/teamauroramods/BetterBadlands/issues"

[[mods]]
    modId="better_badlands"
    version="${file.jarVersion}"
    displayName="Better Badlands"
    displayURL="https://discord.gg/BgE4EpP"
    logoFile="logo.png"
    authors="Team Aurora"
    description="Badlands, but better"

[[dependencies.better_badlands]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_badlands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_badlands]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.2,)"
    ordering="AFTER"
    side="BOTH"
