modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="https://github.com/teamauroramods/BetterBadlands/issues"

[[mods]]
    modId="better_badlands"
    version="1.0.0"
    displayName="Better Badlands"
    displayURL="https://discord.gg/BgE4EpP"
    logoFile="logo.png"
    authors="Team Aurora"
    description="Badlands, but better"

[[dependencies.better_badlands]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.104,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_badlands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_badlands]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[2.0.1,)"
    ordering="AFTER"
    side="BOTH"
